### ISSUE TITLE
Single-Element Tower Abilities

### ISSUE THREAD

**Issue by WindStrike72** [Karawasa/Element-TD#314] opened 2016-03-18 21:28 UTC
Confirmed ones:
- [x] **Fire**: **Blaze** - Short ranged splash attack (like it already is). Each attack applies a single-target DoT debuff on all targets hit, which lasts 3 seconds and just stick any damage numbers on there, I'll fix it up. It's pretty much like Flame Tower's DoT, except all targets hit by the splash attack are affected, and the DoTs are only single-target. But it doesn't linger on the ground if the target dies.
- [x] **Nature**: **Force of Nature** - For each creep within 100 AoE of the target, its damage is increased by 10%. Idea is that this actually synergizes with slowing by becoming more of a sniper tower. Needs a damage pop-up when ability is causing extra damage.
- [x] **Light**: **Intensity** - Long ranged single-target attack (like it already is). Consecutive attacks on the same target causes a flat damage increase (don't worry about numbers). Has no stack limit. Resets completely upon switching. Aka, it's a less broken old versioned **Quark Tower**.
- [x] **Water**: **Water Bullet** - Medium range splash attack (like it already is). Each attack bounces up to 3 times, and unlike Electricity, they can bounce back to the original target (like Luna's passive). Each time it bounces, it loses 50 splash (both Full/Half), similar to how Tidal loses splash. The idea is the second two bounces end up single-target initially, but w/ slowing or vs. undead/temporal, their splash is dealt.
- [x] **Earth**: **Landslide**: Ministun on main target 0.1 seconds. Can happen only once every second. In addition, this is the only tower in the game that hits with a 200/400 AoE attack.
- [x] **Darkness**: **Overkill** - Hits with long range (1150) slow attacks (like it already is). Causes **Overkill**. When it kills a target, any overkill damage on that target transfers to a target within 300 AoE of the target. For example, if it deals 260 damage in one shot, and the target only has 120 hp left, it'll transfer the remaining 140 damage over to a nearby target. This shouldn't proc more than once per attack.

**Comment by vladmarica** [comment] 2016-03-19 19:28
What should the Fire ability be called?

**Comment by WindStrike72** [comment] 2016-03-20 00:38
Call it **Burninatio-** I'm kidding. Go with **Blaze**

**Comment by WindStrike72** [comment] 2016-03-22 20:08
Ooh, new idea for **Light Tower**. We give it **Quark's** old effect, aka gains damage per consecutive attack on the target (not much, just like 5%, and I just calculated, it takes 40+ attacks to get to silly levels of stupidity, which isn't possible w/ Pure Light), has no stack limit, resets completely when it switches targets. BAT would be reverted to 1, damage jumped back up to compensate. It would also naturally shoot furthest target, like **Impulse Tower**, however it would continue to shoot that target until dead or out of range.

**Comment by Karawasa** [comment] 2016-03-22 20:09
Too complicated for Light. Darkness and Fire are simple enough but we want to keep the abilities super basic.

**Comment by vladmarica** [comment] 2016-03-23 10:37
Cool. Could you update the original post when an ability idea is 100% confirmed?

**Comment by WindStrike72** [comment] 2016-03-24 00:27
Done and done. Knocked off the old **Fire** ability, we're keeping these as strictly modifiers of the base attack itself.

**Comment by vladmarica** [comment] 2016-03-24 03:23
Should **Spore Explosion** chain? If it kills a unit, should that unit also trigger another explosion?

**Comment by WindStrike72** [comment] 2016-03-24 04:08
Let's go with yes, it should chain, so that makes it kind of a quasi-flamethrower tower... kinda, but not really.

**Comment by vladmarica** [comment] 2016-03-24 18:38
Spore explosion ability is done logically. Not really happy with the particle effects I made, they are a bit too hard to see, but that's not too important. You can adjust the damage values, the ones I picked seem a bit OP.

**Comment by MNoya** [comment] 2016-03-24 19:42
Should **Blaze** stack? I'm guessing not

**Comment by Karawasa** [comment] 2016-03-24 20:30
Blaze should stack.

**Comment by WindStrike72** [comment] 2016-03-25 12:29
Kay, couldn't come up with an alt for the bouncing thingy for water, go nuts. No idea what to call that ability...

**Comment by MNoya** [comment] 2016-03-25 16:09
We very much need to update today because there's a critical problem with hero replacements.

Also what about a 0.X ministun on the main target of Earth Tower?

**Comment by WindStrike72** [comment] 2016-03-25 18:26
Hmm, we always avoided stuns in the past cause of stunlocking... 
There's a way we could add it, but I'm rather reluctant to doing it, but for the heck of trying it out along with a little warning label that it could be removed:

Mini-stuns the primary target for 0.1 seconds. Also places a buff on the target - cannot be stunned for a full 1 second.

**Comment by MNoya** [comment] 2016-03-25 20:53
All abilities done and tooltip'd, Water & Fire towers are specially over the top now, needs balance playtesting

**Comment by vladmarica** [comment] 2016-03-26 11:24
@WindStrike72 Close this issue once you are happy with the balance.

**Comment by WindStrike72** [comment] 2016-03-26 11:34
Closing for now, twill re-open for next patch.

**Comment by WindStrike72** [comment] 2016-03-27 03:48
Alrighty, bringin' this back, got changes to 2 of 'em for now; **Fire & Earth**, I gotta discuss with some folks about first.

**Water**: Same ability, except each time it bounces, it loses 50 splash (both Full/Half), similar to how **Tidal** loses splash. The idea is the second two bounces end up single-target initially, but w/ slowing or vs. undead/temporal, their splash is dealt.
**Nature:** New ability. It's still a single-target tower. For each creep within 100 AoE of the target, its damage is increased by 10%. Idea is that this actually synergizes with slowing by becoming more of a sniper tower.

**Comment by vladmarica** [comment] 2016-03-27 23:02
Hey @WindStrike72, for the new Nature Tower ability, I increased the search radius to 125. It seems painfully small and ineffective at 100. You can change this back if you'd like. 

Also, if you didn't know, we now have a 'dev' branch where we will do all non-critical development. The new Nature Tower ability is currently only on that branch.

**Comment by vladmarica** [comment] 2016-03-27 23:34
Finished the Water Bullet modification. Just to confirm, since the Water Tower's splash radius is 200/100, the splash on the bounces goes to 150/50 -> 100/0 -> 50/0 ?

**Comment by WindStrike72** [comment] 2016-03-28 03:44
Alrighty, sounds good. And yes, that sounds right on Water Tower, though I'll probably adjust it a little more. Thanks!

**Comment by WindStrike72** [comment] 2016-03-28 04:55
Can we get a damage pop-up for nature tower specifically when it's dealing extra damage?

**Comment by vladmarica** [comment] 2016-03-28 06:00
Sure, I'll do it tomorrow.

**Comment by vladmarica** [comment] 2016-03-28 21:08
There you go @WindStrike72 ! Once again, close this issue once you are happy with the abilities and balance.

**Comment by MNoya** [comment] 2016-03-29 15:25
I don't really like the popups on basically every attack after you have 1 slow and I miss spore explosion particles :disappointed:

**Comment by MNoya** [comment] 2016-03-29 15:28
I think the force of nature popup has to not show up on the first interval at 125 aoe, because right now it shows on every attack when the creeps take a curve even without slows. That or the AoE should be slightly smaller? I don't think increasing its damage without slows in play was intended

**Comment by Karawasa** [comment] 2016-03-31 18:42
Guys I think we need to remove these. They don't feel natural to me. They feel forced and a toned down version of existing towers. Single element is supposed to be pure DPS. The reason is that it helps in planning builds; calculating damage output; and less complexity.

I'm getting a lot of negative feedback from players. I've heard it's harder to figure out what to build. There are now too many tower roles and overlap. I also saw a lot of players ignore the fact that they had abilities. A lot of people have been playing for a long time so they would not expect this.

I think the abilities are great for alternate towers. But I think the solution to single element towers is balance. For instance, darkness at 1 attack speed. Stuff like that makes all element towers playable and each has a different role (without abilities). These abilities make it harder to balance.

**Comment by WindStrike72** [comment] 2016-03-31 21:54
Hmm, I'd like to give one more shot on these. The abilities on Dark, Light and Nature (the new one) are all just modifications. That is, I barely touched their balance, their DPS is practically the same, it just fixes their issues. Dark had a tendency to waste damage horribly, Light didn't synergize/scale well, and Nature didn't synergize with two of its natural builds. I vote to keep these.

The other ones, Fire, Water, and Earth, on the other hand... those are the ones that I try to balance but... ultimately, it would be better if they were just reverted to what they were. Given they're all different amounts of splash and range, they don't really feel nearly as redundant, whereas Dark/Light/Nature just had different ranges and seriously, no one in their right mind would build a Pure Light Tower, yet if I buffed it with a straight damage buff, it'd become too good for the waves.

As we all know, splash towers naturally get way more synergy and support than single target towers. If the abilities are just on the single target ones, and primarily to help our their synergy issues (or in dark's case, fix it for the entire bloody game), yeah people may not actually notice the abilities all that well, but they'll realize something is different when they're actually relevant late-game.

**Comment by Karawasa** [comment] 2016-03-31 22:40
I think it's all or nothing in terms of DLN and EFW. It would be even more confusing if only some single element towers had abilities.

Regarding redundancy, I think it was only one tower not two. Long range slow single target, medium range fast single target. Only got one that is in-between.

Are we fixing something that wasn't really broken? The problem is anytime you do that you introduce other issues.

**Comment by MNoya** [comment] 2016-03-31 23:01
I vote to keep them too, also I don't know where this _lot of negative feedback_ comes from, most people I know thought it was a good idea. Adding more complexity and making what to build harder to figure out are good things generally, if a tower ability is bad/overlaps/broken it can be changed, but axing it altogether is not a good solution now that we implemented & playtested them.

What was broken in my opinion was just "pure DPS towers are boring/unattractive".

**Comment by WindStrike72** [comment] 2016-04-01 10:58
Closing this for now, gonna check out general input from the populace over this next week see what the reactions are before re-opening it.

**Comment by WindStrike72** [comment] 2016-04-06 12:26
Kay, alteration on **Water Tower**..... again. Screw this tower. Anyhow, keep the effect name, here's what it does now.
- Causes **a single bounce** which hits a creep within **150 AoE**. Said bounce deals **25% Damage** with 100/200 AoE. Don't worry about the base damage on the tower.
- Keep a copy of the current ability and just rename it to whatever, we might come back and use it for the Alt Tower Feature.

**Comment by MNoya** [comment] 2016-04-06 14:43
Single Bounce can be done without a dummy (very much like Overkill ability)

**Comment by Karawasa** [comment] 2016-04-07 22:19
Ministun has got to go. New earth tower...

Aftershock. 0.5 seconds after damage, half damage same area.

**Comment by MNoya** [comment] 2016-04-08 00:30
> Ministun has got to go

Is it OP, UP or an unwanted side effect I'm not seeing? I think it synergized well with itself (stacking creeps for further AoE), was is the reasoning behind just doing another AoE instance on the area? That effect also overlaps with Hydro/Flame

**Comment by Karawasa** [comment] 2016-04-08 05:27
It does not scale with the tower levels. It is also out of place for the single element towers (the rest are all damage modifiers).

The Aftershock idea shares some from Hydro but I'm sure it will play different. It will not feel like Flame at all.

**Comment by MNoya** [comment] 2016-04-08 05:42
Only Nature does scale. But yeah I take it that the current earth ability can't be put in damage numbers any easily, I'll change it tomorrow in 5 minutes so it can be playtested

**Closed as completed** 2016-04-13 02:43 UTC
Labels: enhancement, balance, abilities
